apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-autenticacao-deployment
  labels:
    app: api-autenticacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-autenticacao
  template:
    metadata:
      labels:
        app: api-autenticacao
    spec:
      containers:
        - name: api-autenticacao
          image: solinfbroker/api-autenticacao:dev
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresql:5432/database_master"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin"
            - name: SPRING_FLYWAY_BASELINEONMIGRATE
              value: "true"
            - name: SPRING_FLYWAY_TABLE
              value: "schema_version_api_autenticacao"
            - name: SPRING_JPA_HIBERNATE_DDL-AULA
              value: "validate"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION
              value: "true"
            - name: API_SECURITY_TOKEN_SECRET
              value: "teste"
            - name: SERVER_PORT
              value: "8080"

---
apiVersion: v1
kind: Service
metadata:
  name: api-autenticacao-service
spec:
  selector:
    app: api-autenticacao
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: ClusterIP

