apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-crud-deployment
  labels:
    app: api-crud
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-crud
  template:
    metadata:
      labels:
        app: api-crud
    spec:
      containers:
        - name: api-crud
          image: solinfbroker/api-crud:dev
          ports:
            - containerPort: 8081
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgresql:5432/database_master"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "admin"
            - name: SPRING_FLYWAY_BASELINEONMIGRATE
              value: "true"
            - name: SPRING_FLYWAY_TABLE
              value: "schema_version_api_geral"
            - name: SPRING_JPA_HIBERNATE_DDL-AULA
              value: "validate"
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION
              value: "true"
            - name: API_SECURITY_TOKEN_SECRET
              value: "teste"
            - name: SERVER_PORT
              value: "8081"
            - name: API_AUTENTICACAO_PATH
              value: "http://api-autenticacao:8080"
            - name: SPRING_KAFKA_BOOTSTRAP_SERVERS
              value: "kafka:29092"

---
apiVersion: v1
kind: Service
metadata:
  name: api-crud-service
spec:
  selector:
    app: api-crud
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP

