apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-env
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgres-service.dev.svc.cluster.local:5432/database_master"
  SPRING_DATASOURCE_USERNAME: "root"
  SPRING_FLYWAY_BASELINEONMIGRATE: "true"
  SPRING_JPA_HIBERNATE_DDL-AULA: "validate"
  SPRING_JPA_PROPERTIES_HIBERNATE_JDBC_LOB_NON_CONTEXTUAL_CREATION: "true"
  SPRING_KAFKA_BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-service.dev.svc.cluster.local:29092"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: auth-env
data:
  SPRING_FLYWAY_TABLE: "schema_version_api_autenticacao"
  SERVER_PORT: "8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: crud-env
data:
  SPRING_FLYWAY_TABLE: "schema_version_api_geral"
  SERVER_PORT: "8081"
  PATH_API_AUTH: "http://api-autenticacao-service.dev.svc.cluster.local:8080"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: process-env
data:
  SPRING_FLYWAY_TABLE: "schema_version_ms_processamento"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-env
data:
  vue_app_auth_api_url: "http://api-autenticacao-service.dev.svc.cluster.local:8080"
  vue_app_crud_api: "http://api-crud-service.dev.svc.cluster.local:8081"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-init-script
data:
  init.sql: |
    CREATE DATABASE database_master
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zookeeper-env
data:
  ZOOKEEPER_CLIENT_PORT: "2181"
  ZOOKEEPER_TICK_TIME: "2000"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-env
data:
  KAFKA_BROKER_ID: "1"
  KAFKA_ZOOKEEPER_CONNECT: "zookeeper-service.dev.svc.cluster.local:2181"
  # KAFKA_LISTENERS: "PLAINTEXT://:29092,PLAINTEXT_HOST://kafka-service.dev.svc.cluster.local:9092"
  KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://:29092,PLAINTEXT_HOST://kafka-service.dev.svc.cluster.local:9092"
  KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT"
  KAFKA_INTER_BROKER_LISTENER_NAME: "PLAINTEXT"
  KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
  KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
  KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
---

apiVersion: v1
kind: ConfigMap
metadata:
  name: kconnect-env
data:
  CONFIG_STORAGE_TOPIC: "my_connect_configs"
  OFFSET_STORAGE_TOPIC: "my_connect_offsets"
  STATUS_STORAGE_TOPIC: "my_connect_statuses"
  BOOTSTRAP_SERVERS: "PLAINTEXT://kafka-service.dev.svc.cluster.local:9092"

