apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-autenticacao
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-autenticacao
  template:
    metadata:
      labels:
        app: api-autenticacao
    spec:
      containers:
        - name: api-autenticacao
          image: jvlr9510/api_autenticacao:dev
          ports:
            - containerPort: 8080
          envFrom:
            - configMapRef:
                name: api-autenticacao-config
          env:
            - name: SPRING_DATASOURCE_URL
              valueFrom:
                configMapKeyRef:
                  name: api-autenticacao-config
                  key: SPRING_DATASOURCE_URL
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                configMapKeyRef:
                  name: api-autenticacao-config
                  key: SPRING_DATASOURCE_USERNAME
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-autenticacao-secrets
                  key: SPRING_DATASOURCE_PASSWORD
            - name: API_SECURITY_TOKEN_SECRET
              valueFrom:
                secretKeyRef:
                  name: api-autenticacao-secrets
                  key: API_SECURITY_TOKEN_SECRET
            - name: SPRING_FLYWAY_BASELINE_ON_MIGRATE
              valueFrom:
                configMapKeyRef:
                  name: api-autenticacao-config
                  key: SPRING_FLYWAY_BASELINE_ON_MIGRATE
            - name: SPRING_FLYWAY_TABLE
              valueFrom:
                configMapKeyRef:
                  name: api-autenticacao-config
                  key: SPRING_FLYWAY_TABLE
            - name: SERVER_PORT
              valueFrom:
                configMapKeyRef:
                  name: api-autenticacao-config
                  key: SERVER_PORT

