apiVersion: v1
kind: Service
metadata:
  name: api-autenticacao
  namespace: dev
spec:
  selector:
    app: api-autenticacao
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30080
  type: NodePort

