apiVersion: v1
kind: Service
metadata:
  name: api-crud
spec:
  selector:
    app: api-crud
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
      nodePort: 30081
  type: NodePort


