# api-crud-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-crud-service
spec:
  selector:
    app: api-crud
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP

