apiVersion: v1
kind: Service
metadata:
  name: kconnect-service
  labels:
    app: kconnect
spec:
  selector:
    app: kconnect
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP

