# api-autenticacao-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: api-autenticacao-service
spec:
  selector:
    app: api-autenticacao
  ports:
    - protocol: TCP
      port: 8086
      targetPort: 8086
  type: ClusterIP

